CREATE TABLE departments (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code character varying(32) NOT NULL,
    name character varying(128) NOT NULL,
    CONSTRAINT pk_departments PRIMARY KEY (id)
);

CREATE TABLE material_categories (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code character varying(32) NOT NULL,
    name character varying(128) NOT NULL,
    CONSTRAINT pk_material_categories PRIMARY KEY (id)
);

CREATE TABLE product_forms (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code character varying(32) NOT NULL,
    name character varying(128) NOT NULL,
    CONSTRAINT pk_product_forms PRIMARY KEY (id)
);

CREATE TABLE product_types (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code character varying(32) NOT NULL,
    name character varying(128) NOT NULL,
    CONSTRAINT pk_product_types PRIMARY KEY (id)
);

CREATE TABLE production_lines (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code character varying(32) NOT NULL,
    name character varying(128) NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT pk_production_lines PRIMARY KEY (id)
);

CREATE TABLE suppliers (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code character varying(32) NOT NULL,
    name character varying(200) NOT NULL,
    tax_id character varying(16),
    CONSTRAINT pk_suppliers PRIMARY KEY (id)
);

CREATE TABLE user_roles (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code character varying(32) NOT NULL,
    name character varying(128) NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (id)
);

CREATE TABLE raw_materials (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code character varying(32) NOT NULL,
    name character varying(200) NOT NULL,
    unit character varying(16) NOT NULL,
    description character varying(1000),
    status integer NOT NULL,
    material_category_id integer NOT NULL,
    CONSTRAINT pk_raw_materials PRIMARY KEY (id),
    CONSTRAINT fk_raw_materials_material_categories_material_category_id FOREIGN KEY (material_category_id) REFERENCES material_categories (id) ON DELETE RESTRICT
);

CREATE TABLE products (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code character varying(32) NOT NULL,
    name character varying(200) NOT NULL,
    description character varying(1000),
    status integer NOT NULL,
    product_type_id integer NOT NULL,
    product_form_id integer NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT fk_products_product_forms_product_form_id FOREIGN KEY (product_form_id) REFERENCES product_forms (id) ON DELETE RESTRICT,
    CONSTRAINT fk_products_product_types_product_type_id FOREIGN KEY (product_type_id) REFERENCES product_types (id) ON DELETE RESTRICT
);

CREATE TABLE equipment (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    production_line_id integer NOT NULL,
    code character varying(32) NOT NULL,
    name character varying(128) NOT NULL,
    equipment_type integer NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT pk_equipment PRIMARY KEY (id),
    CONSTRAINT fk_equipment_production_lines_production_line_id FOREIGN KEY (production_line_id) REFERENCES production_lines (id) ON DELETE RESTRICT
);

CREATE TABLE app_users (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    login character varying(64) NOT NULL,
    password_hash character varying(256) NOT NULL,
    password_salt character varying(128) NOT NULL,
    full_name character varying(200) NOT NULL,
    email character varying(256),
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_role_id integer NOT NULL,
    department_id integer NOT NULL,
    CONSTRAINT pk_app_users PRIMARY KEY (id),
    CONSTRAINT fk_app_users_departments_department_id FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE RESTRICT,
    CONSTRAINT fk_app_users_user_roles_user_role_id FOREIGN KEY (user_role_id) REFERENCES user_roles (id) ON DELETE RESTRICT
);

CREATE TABLE raw_material_lots (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    raw_material_id integer NOT NULL,
    supplier_id integer NOT NULL,
    internal_lot_number character varying(64) NOT NULL,
    supplier_lot_number character varying(64),
    received_at timestamp with time zone NOT NULL,
    quantity_received numeric(18,3) NOT NULL,
    quantity_available numeric(18,3) NOT NULL,
    storage_location character varying(64) NOT NULL,
    status integer NOT NULL,
    last_laboratory_decision_at timestamp with time zone,
    CONSTRAINT pk_raw_material_lots PRIMARY KEY (id),
    CONSTRAINT ck_raw_material_lots_available_not_greater_than_received CHECK (quantity_available <= quantity_received),
    CONSTRAINT ck_raw_material_lots_quantity_available_positive CHECK (quantity_available >= 0),
    CONSTRAINT ck_raw_material_lots_quantity_received_positive CHECK (quantity_received > 0),
    CONSTRAINT fk_raw_material_lots_raw_materials_raw_material_id FOREIGN KEY (raw_material_id) REFERENCES raw_materials (id) ON DELETE RESTRICT,
    CONSTRAINT fk_raw_material_lots_suppliers_supplier_id FOREIGN KEY (supplier_id) REFERENCES suppliers (id) ON DELETE RESTRICT
);

CREATE TABLE quality_specifications (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code character varying(32) NOT NULL,
    name character varying(200) NOT NULL,
    subject_type integer NOT NULL,
    raw_material_id integer,
    product_id integer,
    version_number integer NOT NULL,
    status integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_quality_specifications PRIMARY KEY (id),
    CONSTRAINT ck_quality_specifications_active_requires_approved_status CHECK (NOT is_active OR status = 2),
    CONSTRAINT ck_quality_specifications_subject CHECK (((subject_type = 1 AND raw_material_id IS NOT NULL AND product_id IS NULL) OR (subject_type = 2 AND product_id IS NOT NULL AND raw_material_id IS NULL))),
    CONSTRAINT ck_quality_specifications_version_positive CHECK (version_number > 0),
    CONSTRAINT fk_quality_specifications_products_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
    CONSTRAINT fk_quality_specifications_raw_materials_raw_material_id FOREIGN KEY (raw_material_id) REFERENCES raw_materials (id) ON DELETE RESTRICT
);

CREATE TABLE audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    entity_type character varying(64) NOT NULL,
    entity_id integer NOT NULL,
    action_name character varying(64) NOT NULL,
    occurred_at timestamp with time zone NOT NULL,
    acting_user_id integer,
    details character varying(2000),
    CONSTRAINT pk_audit_events PRIMARY KEY (id),
    CONSTRAINT ck_audit_events_entity_type CHECK (entity_type IN ('RecipeVersion', 'TechnologyCard', 'ProductionOrder', 'ProductionBatch', 'RawMaterialLot', 'LaboratoryTest', 'ProcessDeviation', 'QualityDecision')),
    CONSTRAINT fk_audit_events_app_users_acting_user_id FOREIGN KEY (acting_user_id) REFERENCES app_users (id) ON DELETE RESTRICT
);

CREATE TABLE notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    recipient_user_id integer NOT NULL,
    entity_type character varying(64) NOT NULL,
    entity_id integer NOT NULL,
    message character varying(500) NOT NULL,
    severity integer NOT NULL,
    is_read boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    read_at timestamp with time zone,
    CONSTRAINT pk_notifications PRIMARY KEY (id),
    CONSTRAINT ck_notifications_entity_type CHECK (entity_type IN ('RecipeVersion', 'TechnologyCard', 'ProductionOrder', 'ProductionBatch', 'RawMaterialLot', 'LaboratoryTest', 'ProcessDeviation', 'QualityDecision')),
    CONSTRAINT ck_notifications_read_timestamp CHECK (read_at IS NULL OR is_read),
    CONSTRAINT fk_notifications_app_users_recipient_user_id FOREIGN KEY (recipient_user_id) REFERENCES app_users (id) ON DELETE RESTRICT
);

CREATE TABLE production_orders (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    order_number character varying(64) NOT NULL,
    product_id integer NOT NULL,
    production_line_id integer NOT NULL,
    planned_quantity numeric(18,3) NOT NULL,
    planned_start_at timestamp with time zone,
    status integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by_user_id integer NOT NULL,
    CONSTRAINT pk_production_orders PRIMARY KEY (id),
    CONSTRAINT ak_production_orders_id_product_id_production_line_id UNIQUE (id, product_id, production_line_id),
    CONSTRAINT ck_production_orders_planned_quantity_positive CHECK (planned_quantity > 0),
    CONSTRAINT fk_production_orders_app_users_created_by_user_id FOREIGN KEY (created_by_user_id) REFERENCES app_users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_production_orders_production_lines_production_line_id FOREIGN KEY (production_line_id) REFERENCES production_lines (id) ON DELETE RESTRICT,
    CONSTRAINT fk_production_orders_products_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT
);

CREATE TABLE recipe_versions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    product_id integer NOT NULL,
    version_number integer NOT NULL,
    status integer NOT NULL,
    is_active boolean NOT NULL,
    notes character varying(1000),
    created_at timestamp with time zone NOT NULL,
    created_by_user_id integer NOT NULL,
    approved_at timestamp with time zone,
    approved_by_user_id integer,
    CONSTRAINT pk_recipe_versions PRIMARY KEY (id),
    CONSTRAINT ak_recipe_versions_id_product_id UNIQUE (id, product_id),
    CONSTRAINT ck_recipe_versions_active_requires_approved_status CHECK (NOT is_active OR status = 3),
    CONSTRAINT ck_recipe_versions_approved_requires_metadata CHECK (status <> 3 OR (approved_at IS NOT NULL AND approved_by_user_id IS NOT NULL)),
    CONSTRAINT ck_recipe_versions_version_number_positive CHECK (version_number > 0),
    CONSTRAINT fk_recipe_versions_app_users_approved_by_user_id FOREIGN KEY (approved_by_user_id) REFERENCES app_users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_recipe_versions_app_users_created_by_user_id FOREIGN KEY (created_by_user_id) REFERENCES app_users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_recipe_versions_products_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT
);

CREATE TABLE status_histories (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    entity_type character varying(64) NOT NULL,
    entity_id integer NOT NULL,
    previous_status character varying(64),
    new_status character varying(64) NOT NULL,
    changed_at timestamp with time zone NOT NULL,
    changed_by_user_id integer,
    comment character varying(1000),
    CONSTRAINT pk_status_histories PRIMARY KEY (id),
    CONSTRAINT ck_status_histories_entity_type CHECK (entity_type IN ('RecipeVersion', 'TechnologyCard', 'ProductionOrder', 'ProductionBatch', 'RawMaterialLot', 'LaboratoryTest', 'ProcessDeviation', 'QualityDecision')),
    CONSTRAINT ck_status_histories_new_status_not_empty CHECK (length(trim(new_status)) > 0),
    CONSTRAINT fk_status_histories_app_users_changed_by_user_id FOREIGN KEY (changed_by_user_id) REFERENCES app_users (id) ON DELETE RESTRICT
);

CREATE TABLE technology_cards (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    product_id integer NOT NULL,
    version_number integer NOT NULL,
    title character varying(200) NOT NULL,
    description character varying(1000),
    status integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by_user_id integer NOT NULL,
    approved_at timestamp with time zone,
    approved_by_user_id integer,
    CONSTRAINT pk_technology_cards PRIMARY KEY (id),
    CONSTRAINT ak_technology_cards_id_product_id UNIQUE (id, product_id),
    CONSTRAINT ck_technology_cards_active_requires_approved_status CHECK (NOT is_active OR status = 3),
    CONSTRAINT ck_technology_cards_approved_requires_metadata CHECK (status <> 3 OR (approved_at IS NOT NULL AND approved_by_user_id IS NOT NULL)),
    CONSTRAINT ck_technology_cards_version_number_positive CHECK (version_number > 0),
    CONSTRAINT fk_technology_cards_app_users_approved_by_user_id FOREIGN KEY (approved_by_user_id) REFERENCES app_users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_technology_cards_app_users_created_by_user_id FOREIGN KEY (created_by_user_id) REFERENCES app_users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_technology_cards_products_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT
);

CREATE TABLE quality_specification_parameters (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    quality_specification_id integer NOT NULL,
    sort_order integer NOT NULL,
    name character varying(128) NOT NULL,
    value_type integer NOT NULL,
    unit character varying(16),
    min_numeric_value numeric(18,3),
    max_numeric_value numeric(18,3),
    target_text_value character varying(256),
    target_boolean_value boolean,
    is_required boolean NOT NULL,
    CONSTRAINT pk_quality_specification_parameters PRIMARY KEY (id),
    CONSTRAINT ck_quality_specification_parameters_numeric_range CHECK (min_numeric_value IS NULL OR max_numeric_value IS NULL OR min_numeric_value <= max_numeric_value),
    CONSTRAINT ck_quality_specification_parameters_sort_order_positive CHECK (sort_order > 0),
    CONSTRAINT ck_quality_specification_parameters_value_type_targets CHECK (CASE WHEN value_type = 1 THEN (min_numeric_value IS NOT NULL OR max_numeric_value IS NOT NULL) WHEN value_type = 2 THEN target_text_value IS NOT NULL WHEN value_type = 3 THEN target_boolean_value IS NOT NULL ELSE FALSE END),
    CONSTRAINT fk_quality_specification_parameters_quality_specifications_qua FOREIGN KEY (quality_specification_id) REFERENCES quality_specifications (id) ON DELETE CASCADE
);

CREATE TABLE recipe_components (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    recipe_version_id integer NOT NULL,
    raw_material_id integer NOT NULL,
    percentage numeric(5,2) NOT NULL,
    load_order integer NOT NULL,
    allowed_deviation_percent numeric(5,2) NOT NULL,
    CONSTRAINT pk_recipe_components PRIMARY KEY (id),
    CONSTRAINT ck_recipe_components_allowed_deviation_range CHECK (allowed_deviation_percent >= 0 AND allowed_deviation_percent <= 100),
    CONSTRAINT ck_recipe_components_load_order_positive CHECK (load_order > 0),
    CONSTRAINT ck_recipe_components_percentage_range CHECK (percentage > 0 AND percentage <= 100),
    CONSTRAINT fk_recipe_components_raw_materials_raw_material_id FOREIGN KEY (raw_material_id) REFERENCES raw_materials (id) ON DELETE RESTRICT,
    CONSTRAINT fk_recipe_components_recipe_versions_recipe_version_id FOREIGN KEY (recipe_version_id) REFERENCES recipe_versions (id) ON DELETE CASCADE
);

CREATE TABLE extruder_programs (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    product_id integer NOT NULL,
    technology_card_id integer,
    code character varying(32) NOT NULL,
    name character varying(200) NOT NULL,
    version_number integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    notes character varying(1000),
    CONSTRAINT pk_extruder_programs PRIMARY KEY (id),
    CONSTRAINT ak_extruder_programs_id_product_id UNIQUE (id, product_id),
    CONSTRAINT ck_extruder_programs_version_number_positive CHECK (version_number > 0),
    CONSTRAINT fk_extruder_programs_products_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
    CONSTRAINT fk_extruder_programs_technology_cards_technology_card_id_produ FOREIGN KEY (technology_card_id, product_id) REFERENCES technology_cards (id, product_id) ON DELETE RESTRICT
);

CREATE TABLE technology_steps (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    technology_card_id integer NOT NULL,
    step_order integer NOT NULL,
    step_type integer NOT NULL,
    title character varying(200) NOT NULL,
    instruction character varying(2000),
    is_required boolean NOT NULL,
    expected_duration_minutes integer,
    CONSTRAINT pk_technology_steps PRIMARY KEY (id),
    CONSTRAINT ck_technology_steps_expected_duration_positive CHECK (expected_duration_minutes IS NULL OR expected_duration_minutes > 0),
    CONSTRAINT ck_technology_steps_step_order_positive CHECK (step_order > 0),
    CONSTRAINT fk_technology_steps_technology_cards_technology_card_id FOREIGN KEY (technology_card_id) REFERENCES technology_cards (id) ON DELETE CASCADE
);

CREATE TABLE extruder_program_parameters (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    extruder_program_id integer NOT NULL,
    sort_order integer NOT NULL,
    zone_number integer,
    name character varying(128) NOT NULL,
    value_type integer NOT NULL,
    target_numeric_value numeric(18,3),
    target_text_value character varying(256),
    target_boolean_value boolean,
    unit character varying(16),
    CONSTRAINT pk_extruder_program_parameters PRIMARY KEY (id),
    CONSTRAINT ck_extruder_program_parameters_sort_order_positive CHECK (sort_order > 0),
    CONSTRAINT ck_extruder_program_parameters_value_type_targets CHECK (CASE WHEN value_type = 1 THEN target_numeric_value IS NOT NULL WHEN value_type = 2 THEN target_text_value IS NOT NULL WHEN value_type = 3 THEN target_boolean_value IS NOT NULL ELSE FALSE END),
    CONSTRAINT ck_extruder_program_parameters_zone_number_positive CHECK (zone_number IS NULL OR zone_number > 0),
    CONSTRAINT fk_extruder_program_parameters_extruder_programs_extruder_prog FOREIGN KEY (extruder_program_id) REFERENCES extruder_programs (id) ON DELETE CASCADE
);

CREATE TABLE production_batches (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    batch_number character varying(64) NOT NULL,
    production_order_id integer,
    product_id integer NOT NULL,
    recipe_version_id integer NOT NULL,
    technology_card_id integer NOT NULL,
    production_line_id integer NOT NULL,
    extruder_program_id integer,
    planned_quantity numeric(18,3) NOT NULL,
    status integer NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    CONSTRAINT pk_production_batches PRIMARY KEY (id),
    CONSTRAINT ck_production_batches_completed_after_start CHECK (completed_at IS NULL OR completed_at >= started_at),
    CONSTRAINT ck_production_batches_completed_requires_start CHECK (completed_at IS NULL OR started_at IS NOT NULL),
    CONSTRAINT ck_production_batches_completed_status_requires_completed_at CHECK (status <> 6 OR completed_at IS NOT NULL),
    CONSTRAINT ck_production_batches_planned_quantity_positive CHECK (planned_quantity > 0),
    CONSTRAINT fk_production_batches_extruder_programs_extruder_program_id_pr FOREIGN KEY (extruder_program_id, product_id) REFERENCES extruder_programs (id, product_id) ON DELETE RESTRICT,
    CONSTRAINT fk_production_batches_production_lines_production_line_id FOREIGN KEY (production_line_id) REFERENCES production_lines (id) ON DELETE RESTRICT,
    CONSTRAINT fk_production_batches_production_orders_production_order_id_pr FOREIGN KEY (production_order_id, product_id, production_line_id) REFERENCES production_orders (id, product_id, production_line_id) ON DELETE RESTRICT,
    CONSTRAINT fk_production_batches_products_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
    CONSTRAINT fk_production_batches_recipe_versions_recipe_version_id_produc FOREIGN KEY (recipe_version_id, product_id) REFERENCES recipe_versions (id, product_id) ON DELETE RESTRICT,
    CONSTRAINT fk_production_batches_technology_cards_technology_card_id_prod FOREIGN KEY (technology_card_id, product_id) REFERENCES technology_cards (id, product_id) ON DELETE RESTRICT
);

CREATE TABLE technology_step_parameters (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    technology_step_id integer NOT NULL,
    name character varying(128) NOT NULL,
    value_type integer NOT NULL,
    unit character varying(16),
    target_numeric_value numeric(18,3),
    min_numeric_value numeric(18,3),
    max_numeric_value numeric(18,3),
    target_text_value character varying(256),
    target_boolean_value boolean,
    is_required boolean NOT NULL,
    comment character varying(1000),
    CONSTRAINT pk_technology_step_parameters PRIMARY KEY (id),
    CONSTRAINT ck_technology_step_parameters_numeric_range CHECK (min_numeric_value IS NULL OR max_numeric_value IS NULL OR min_numeric_value <= max_numeric_value),
    CONSTRAINT ck_technology_step_parameters_value_type_targets CHECK (CASE WHEN value_type = 1 THEN (target_numeric_value IS NOT NULL OR min_numeric_value IS NOT NULL OR max_numeric_value IS NOT NULL) WHEN value_type = 2 THEN target_text_value IS NOT NULL WHEN value_type = 3 THEN target_boolean_value IS NOT NULL ELSE FALSE END),
    CONSTRAINT fk_technology_step_parameters_technology_steps_technology_step FOREIGN KEY (technology_step_id) REFERENCES technology_steps (id) ON DELETE CASCADE
);

CREATE TABLE batch_raw_material_consumptions (
    production_batch_id integer NOT NULL,
    raw_material_lot_id integer NOT NULL,
    quantity_used numeric(18,3) NOT NULL,
    CONSTRAINT pk_batch_raw_material_consumptions PRIMARY KEY (production_batch_id, raw_material_lot_id),
    CONSTRAINT ck_batch_raw_material_consumptions_quantity_positive CHECK (quantity_used > 0),
    CONSTRAINT fk_batch_raw_material_consumptions_production_batches_producti FOREIGN KEY (production_batch_id) REFERENCES production_batches (id) ON DELETE CASCADE,
    CONSTRAINT fk_batch_raw_material_consumptions_raw_material_lots_raw_mater FOREIGN KEY (raw_material_lot_id) REFERENCES raw_material_lots (id) ON DELETE RESTRICT
);

CREATE TABLE batch_technology_step_runs (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    production_batch_id integer NOT NULL,
    technology_step_id integer NOT NULL,
    status integer NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    started_by_user_id integer,
    completed_by_user_id integer,
    comment character varying(1000),
    CONSTRAINT pk_batch_technology_step_runs PRIMARY KEY (id),
    CONSTRAINT ck_batch_technology_step_runs_completed_after_start CHECK (completed_at IS NULL OR completed_at >= started_at),
    CONSTRAINT ck_batch_technology_step_runs_completed_requires_completed_by CHECK (status <> 3 OR (completed_at IS NOT NULL AND completed_by_user_id IS NOT NULL)),
    CONSTRAINT ck_batch_technology_step_runs_completed_requires_start CHECK (completed_at IS NULL OR started_at IS NOT NULL),
    CONSTRAINT ck_batch_technology_step_runs_in_progress_requires_started_by CHECK (status <> 2 OR (started_at IS NOT NULL AND started_by_user_id IS NOT NULL)),
    CONSTRAINT fk_batch_technology_step_runs_app_users_completed_by_user_id FOREIGN KEY (completed_by_user_id) REFERENCES app_users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_batch_technology_step_runs_app_users_started_by_user_id FOREIGN KEY (started_by_user_id) REFERENCES app_users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_batch_technology_step_runs_production_batches_production_ba FOREIGN KEY (production_batch_id) REFERENCES production_batches (id) ON DELETE CASCADE,
    CONSTRAINT fk_batch_technology_step_runs_technology_steps_technology_step FOREIGN KEY (technology_step_id) REFERENCES technology_steps (id) ON DELETE RESTRICT
);

CREATE TABLE equipment_telemetry_readings (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    production_batch_id integer NOT NULL,
    equipment_id integer,
    zone_name character varying(64) NOT NULL,
    metric_name character varying(64) NOT NULL,
    numeric_value numeric(18,3) NOT NULL,
    unit character varying(16),
    severity integer NOT NULL,
    recorded_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_equipment_telemetry_readings PRIMARY KEY (id),
    CONSTRAINT fk_equipment_telemetry_readings_equipment_equipment_id FOREIGN KEY (equipment_id) REFERENCES equipment (id) ON DELETE RESTRICT,
    CONSTRAINT fk_equipment_telemetry_readings_production_batches_production_ FOREIGN KEY (production_batch_id) REFERENCES production_batches (id) ON DELETE CASCADE
);

CREATE TABLE laboratory_tests (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    test_number character varying(64) NOT NULL,
    subject_type integer NOT NULL,
    raw_material_lot_id integer,
    production_batch_id integer,
    quality_specification_id integer NOT NULL,
    test_kind character varying(128) NOT NULL,
    status integer NOT NULL,
    priority integer NOT NULL,
    comment character varying(1000),
    result_summary character varying(1000),
    created_at timestamp with time zone NOT NULL,
    assigned_at timestamp with time zone,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    tester_user_id integer,
    CONSTRAINT pk_laboratory_tests PRIMARY KEY (id),
    CONSTRAINT ck_laboratory_tests_assigned_after_created CHECK (assigned_at IS NULL OR assigned_at >= created_at),
    CONSTRAINT ck_laboratory_tests_completed_after_start CHECK (completed_at IS NULL OR completed_at >= started_at),
    CONSTRAINT ck_laboratory_tests_completed_requires_start CHECK (completed_at IS NULL OR started_at IS NOT NULL),
    CONSTRAINT ck_laboratory_tests_completed_requires_tester CHECK (status <> 3 OR (completed_at IS NOT NULL AND tester_user_id IS NOT NULL)),
    CONSTRAINT ck_laboratory_tests_in_progress_requires_tester CHECK (status <> 2 OR (started_at IS NOT NULL AND tester_user_id IS NOT NULL)),
    CONSTRAINT ck_laboratory_tests_started_after_created CHECK (started_at IS NULL OR started_at >= created_at),
    CONSTRAINT ck_laboratory_tests_subject CHECK (((subject_type = 1 AND raw_material_lot_id IS NOT NULL AND production_batch_id IS NULL) OR (subject_type = 2 AND production_batch_id IS NOT NULL AND raw_material_lot_id IS NULL))),
    CONSTRAINT fk_laboratory_tests_app_users_tester_user_id FOREIGN KEY (tester_user_id) REFERENCES app_users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_laboratory_tests_production_batches_production_batch_id FOREIGN KEY (production_batch_id) REFERENCES production_batches (id) ON DELETE RESTRICT,
    CONSTRAINT fk_laboratory_tests_quality_specifications_quality_specificati FOREIGN KEY (quality_specification_id) REFERENCES quality_specifications (id) ON DELETE RESTRICT,
    CONSTRAINT fk_laboratory_tests_raw_material_lots_raw_material_lot_id FOREIGN KEY (raw_material_lot_id) REFERENCES raw_material_lots (id) ON DELETE RESTRICT
);

CREATE TABLE batch_step_measured_values (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    batch_technology_step_run_id integer NOT NULL,
    technology_step_parameter_id integer NOT NULL,
    actual_numeric_value numeric(18,3),
    actual_text_value character varying(256),
    actual_boolean_value boolean,
    is_within_tolerance boolean,
    recorded_at timestamp with time zone NOT NULL,
    comment character varying(1000),
    CONSTRAINT pk_batch_step_measured_values PRIMARY KEY (id),
    CONSTRAINT ck_batch_step_measured_values_single_actual_value CHECK (num_nonnulls(actual_numeric_value, actual_text_value, actual_boolean_value) = 1),
    CONSTRAINT fk_batch_step_measured_values_batch_technology_step_runs_batch FOREIGN KEY (batch_technology_step_run_id) REFERENCES batch_technology_step_runs (id) ON DELETE CASCADE,
    CONSTRAINT fk_batch_step_measured_values_technology_step_parameters_techn FOREIGN KEY (technology_step_parameter_id) REFERENCES technology_step_parameters (id) ON DELETE RESTRICT
);

CREATE TABLE process_deviations (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    production_batch_id integer NOT NULL,
    batch_technology_step_run_id integer,
    title character varying(200) NOT NULL,
    parameter_name character varying(128),
    planned_value character varying(256),
    actual_value character varying(256),
    severity integer NOT NULL,
    details character varying(2000),
    created_at timestamp with time zone NOT NULL,
    reported_by_user_id integer,
    CONSTRAINT pk_process_deviations PRIMARY KEY (id),
    CONSTRAINT fk_process_deviations_app_users_reported_by_user_id FOREIGN KEY (reported_by_user_id) REFERENCES app_users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_process_deviations_batch_technology_step_runs_batch_technol FOREIGN KEY (batch_technology_step_run_id) REFERENCES batch_technology_step_runs (id) ON DELETE RESTRICT,
    CONSTRAINT fk_process_deviations_production_batches_production_batch_id FOREIGN KEY (production_batch_id) REFERENCES production_batches (id) ON DELETE CASCADE
);

CREATE TABLE laboratory_test_parameter_results (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    laboratory_test_id integer NOT NULL,
    quality_specification_parameter_id integer,
    sort_order integer NOT NULL,
    parameter_name character varying(128) NOT NULL,
    value_type integer NOT NULL,
    unit character varying(16),
    min_numeric_value numeric(18,3),
    max_numeric_value numeric(18,3),
    target_text_value character varying(256),
    target_boolean_value boolean,
    actual_numeric_value numeric(18,3),
    actual_text_value character varying(256),
    actual_boolean_value boolean,
    is_required boolean NOT NULL,
    is_within_range boolean,
    comment character varying(1000),
    CONSTRAINT pk_laboratory_test_parameter_results PRIMARY KEY (id),
    CONSTRAINT ck_laboratory_test_parameter_results_numeric_range CHECK (min_numeric_value IS NULL OR max_numeric_value IS NULL OR min_numeric_value <= max_numeric_value),
    CONSTRAINT ck_laboratory_test_parameter_results_single_actual_value CHECK (num_nonnulls(actual_numeric_value, actual_text_value, actual_boolean_value) <= 1),
    CONSTRAINT ck_laboratory_test_parameter_results_sort_order_positive CHECK (sort_order > 0),
    CONSTRAINT ck_laboratory_test_parameter_results_value_type_compatibility CHECK (CASE WHEN value_type = 1 THEN actual_text_value IS NULL AND actual_boolean_value IS NULL WHEN value_type = 2 THEN actual_numeric_value IS NULL AND actual_boolean_value IS NULL WHEN value_type = 3 THEN actual_numeric_value IS NULL AND actual_text_value IS NULL ELSE FALSE END),
    CONSTRAINT fk_laboratory_test_parameter_results_laboratory_tests_laborato FOREIGN KEY (laboratory_test_id) REFERENCES laboratory_tests (id) ON DELETE CASCADE,
    CONSTRAINT fk_laboratory_test_parameter_results_quality_specification_par FOREIGN KEY (quality_specification_parameter_id) REFERENCES quality_specification_parameters (id) ON DELETE RESTRICT
);

CREATE TABLE quality_decisions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    subject_type integer NOT NULL,
    raw_material_lot_id integer,
    production_batch_id integer,
    laboratory_test_id integer NOT NULL,
    decision_status integer NOT NULL,
    comment character varying(1000),
    block_reason character varying(1000),
    is_current boolean NOT NULL,
    decided_at timestamp with time zone NOT NULL,
    decided_by_user_id integer NOT NULL,
    CONSTRAINT pk_quality_decisions PRIMARY KEY (id),
    CONSTRAINT ck_quality_decisions_block_reason_required CHECK (decision_status <> 2 OR block_reason IS NOT NULL),
    CONSTRAINT ck_quality_decisions_comment_required CHECK (comment IS NOT NULL),
    CONSTRAINT ck_quality_decisions_subject CHECK (((subject_type = 1 AND raw_material_lot_id IS NOT NULL AND production_batch_id IS NULL) OR (subject_type = 2 AND production_batch_id IS NOT NULL AND raw_material_lot_id IS NULL))),
    CONSTRAINT fk_quality_decisions_app_users_decided_by_user_id FOREIGN KEY (decided_by_user_id) REFERENCES app_users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_quality_decisions_laboratory_tests_laboratory_test_id FOREIGN KEY (laboratory_test_id) REFERENCES laboratory_tests (id) ON DELETE RESTRICT,
    CONSTRAINT fk_quality_decisions_production_batches_production_batch_id FOREIGN KEY (production_batch_id) REFERENCES production_batches (id) ON DELETE RESTRICT,
    CONSTRAINT fk_quality_decisions_raw_material_lots_raw_material_lot_id FOREIGN KEY (raw_material_lot_id) REFERENCES raw_material_lots (id) ON DELETE RESTRICT
);


CREATE INDEX ix_app_users_department_id ON app_users (department_id);

CREATE UNIQUE INDEX ix_app_users_email ON app_users (email);

CREATE UNIQUE INDEX ix_app_users_login ON app_users (login);

CREATE INDEX ix_app_users_user_role_id ON app_users (user_role_id);

CREATE INDEX ix_audit_events_acting_user_id ON audit_events (acting_user_id);

CREATE INDEX ix_audit_events_entity_type_entity_id_occurred_at ON audit_events (entity_type, entity_id, occurred_at);

CREATE INDEX ix_batch_raw_material_consumptions_raw_material_lot_id ON batch_raw_material_consumptions (raw_material_lot_id);

CREATE UNIQUE INDEX ix_batch_step_measured_values_batch_technology_step_run_id_tec ON batch_step_measured_values (batch_technology_step_run_id, technology_step_parameter_id);

CREATE INDEX ix_batch_step_measured_values_technology_step_parameter_id ON batch_step_measured_values (technology_step_parameter_id);

CREATE INDEX ix_batch_technology_step_runs_completed_by_user_id ON batch_technology_step_runs (completed_by_user_id);

CREATE UNIQUE INDEX ix_batch_technology_step_runs_production_batch_id_technology_s ON batch_technology_step_runs (production_batch_id, technology_step_id);

CREATE INDEX ix_batch_technology_step_runs_started_by_user_id ON batch_technology_step_runs (started_by_user_id);

CREATE INDEX ix_batch_technology_step_runs_technology_step_id ON batch_technology_step_runs (technology_step_id);

CREATE UNIQUE INDEX ix_departments_code ON departments (code);

CREATE UNIQUE INDEX ix_departments_name ON departments (name);

CREATE UNIQUE INDEX ix_equipment_code ON equipment (code);

CREATE INDEX ix_equipment_production_line_id ON equipment (production_line_id);

CREATE INDEX ix_equipment_telemetry_readings_equipment_id ON equipment_telemetry_readings (equipment_id);

CREATE INDEX ix_equipment_telemetry_readings_production_batch_id_recorded_at ON equipment_telemetry_readings (production_batch_id, recorded_at);

CREATE UNIQUE INDEX ix_extruder_program_parameters_extruder_program_id_sort_order ON extruder_program_parameters (extruder_program_id, sort_order);

CREATE UNIQUE INDEX ix_extruder_programs_product_id_code_version_number ON extruder_programs (product_id, code, version_number);

CREATE INDEX ix_extruder_programs_technology_card_id_product_id ON extruder_programs (technology_card_id, product_id);

CREATE UNIQUE INDEX ix_laboratory_test_parameter_results_laboratory_test_id_sort_o ON laboratory_test_parameter_results (laboratory_test_id, sort_order);

CREATE INDEX ix_laboratory_test_parameter_results_quality_specification_par ON laboratory_test_parameter_results (quality_specification_parameter_id);

CREATE INDEX ix_laboratory_tests_production_batch_id ON laboratory_tests (production_batch_id);

CREATE INDEX ix_laboratory_tests_quality_specification_id ON laboratory_tests (quality_specification_id);

CREATE INDEX ix_laboratory_tests_raw_material_lot_id ON laboratory_tests (raw_material_lot_id);

CREATE INDEX ix_laboratory_tests_subject_type_raw_material_lot_id_productio ON laboratory_tests (subject_type, raw_material_lot_id, production_batch_id);

CREATE UNIQUE INDEX ix_laboratory_tests_test_number ON laboratory_tests (test_number);

CREATE INDEX ix_laboratory_tests_tester_user_id ON laboratory_tests (tester_user_id);

CREATE UNIQUE INDEX ix_material_categories_code ON material_categories (code);

CREATE UNIQUE INDEX ix_material_categories_name ON material_categories (name);

CREATE INDEX ix_notifications_recipient_user_id_is_read_created_at ON notifications (recipient_user_id, is_read, created_at);

CREATE INDEX ix_process_deviations_batch_technology_step_run_id ON process_deviations (batch_technology_step_run_id);

CREATE INDEX ix_process_deviations_production_batch_id_created_at ON process_deviations (production_batch_id, created_at);

CREATE INDEX ix_process_deviations_reported_by_user_id ON process_deviations (reported_by_user_id);

CREATE UNIQUE INDEX ix_product_forms_code ON product_forms (code);

CREATE UNIQUE INDEX ix_product_forms_name ON product_forms (name);

CREATE UNIQUE INDEX ix_product_types_code ON product_types (code);

CREATE UNIQUE INDEX ix_product_types_name ON product_types (name);

CREATE UNIQUE INDEX ix_production_batches_batch_number ON production_batches (batch_number);

CREATE INDEX ix_production_batches_extruder_program_id_product_id ON production_batches (extruder_program_id, product_id);

CREATE INDEX ix_production_batches_product_id_status ON production_batches (product_id, status);

CREATE INDEX ix_production_batches_production_line_id ON production_batches (production_line_id);

CREATE INDEX ix_production_batches_production_order_id_product_id_productio ON production_batches (production_order_id, product_id, production_line_id);

CREATE INDEX ix_production_batches_recipe_version_id_product_id ON production_batches (recipe_version_id, product_id);

CREATE INDEX ix_production_batches_technology_card_id_product_id ON production_batches (technology_card_id, product_id);

CREATE UNIQUE INDEX ix_production_lines_code ON production_lines (code);

CREATE UNIQUE INDEX ix_production_lines_name ON production_lines (name);

CREATE INDEX ix_production_orders_created_by_user_id ON production_orders (created_by_user_id);

CREATE UNIQUE INDEX ix_production_orders_order_number ON production_orders (order_number);

CREATE INDEX ix_production_orders_product_id_status ON production_orders (product_id, status);

CREATE INDEX ix_production_orders_production_line_id ON production_orders (production_line_id);

CREATE UNIQUE INDEX ix_products_code ON products (code);

CREATE UNIQUE INDEX ix_products_name ON products (name);

CREATE INDEX ix_products_product_form_id ON products (product_form_id);

CREATE INDEX ix_products_product_type_id ON products (product_type_id);

CREATE INDEX ix_quality_decisions_decided_by_user_id ON quality_decisions (decided_by_user_id);

CREATE INDEX ix_quality_decisions_laboratory_test_id ON quality_decisions (laboratory_test_id);

CREATE UNIQUE INDEX ix_quality_decisions_production_batch_id ON quality_decisions (production_batch_id) WHERE is_current AND production_batch_id IS NOT NULL;

CREATE UNIQUE INDEX ix_quality_decisions_raw_material_lot_id ON quality_decisions (raw_material_lot_id) WHERE is_current AND raw_material_lot_id IS NOT NULL;

CREATE UNIQUE INDEX ix_quality_specification_parameters_quality_specification_id_n ON quality_specification_parameters (quality_specification_id, name);

CREATE UNIQUE INDEX ix_quality_specification_parameters_quality_specification_id_s ON quality_specification_parameters (quality_specification_id, sort_order);

CREATE UNIQUE INDEX ix_quality_specifications_code_version_number ON quality_specifications (code, version_number);

CREATE UNIQUE INDEX ix_quality_specifications_product_id ON quality_specifications (product_id) WHERE subject_type = 2 AND status = 2 AND is_active AND product_id IS NOT NULL;

CREATE UNIQUE INDEX ix_quality_specifications_raw_material_id ON quality_specifications (raw_material_id) WHERE subject_type = 1 AND status = 2 AND is_active AND raw_material_id IS NOT NULL;

CREATE UNIQUE INDEX ix_raw_material_lots_internal_lot_number ON raw_material_lots (internal_lot_number);

CREATE INDEX ix_raw_material_lots_raw_material_id_status ON raw_material_lots (raw_material_id, status);

CREATE UNIQUE INDEX ix_raw_material_lots_supplier_id_supplier_lot_number ON raw_material_lots (supplier_id, supplier_lot_number);

CREATE UNIQUE INDEX ix_raw_materials_code ON raw_materials (code);

CREATE INDEX ix_raw_materials_material_category_id ON raw_materials (material_category_id);

CREATE UNIQUE INDEX ix_raw_materials_name ON raw_materials (name);

CREATE INDEX ix_recipe_components_raw_material_id ON recipe_components (raw_material_id);

CREATE UNIQUE INDEX ix_recipe_components_recipe_version_id_load_order ON recipe_components (recipe_version_id, load_order);

CREATE UNIQUE INDEX ix_recipe_components_recipe_version_id_raw_material_id ON recipe_components (recipe_version_id, raw_material_id);

CREATE INDEX ix_recipe_versions_approved_by_user_id ON recipe_versions (approved_by_user_id);

CREATE INDEX ix_recipe_versions_created_by_user_id ON recipe_versions (created_by_user_id);

CREATE UNIQUE INDEX ix_recipe_versions_product_id ON recipe_versions (product_id) WHERE status = 3 AND is_active;

CREATE UNIQUE INDEX ix_recipe_versions_product_id_version_number ON recipe_versions (product_id, version_number);

CREATE INDEX ix_status_histories_changed_by_user_id ON status_histories (changed_by_user_id);

CREATE INDEX ix_status_histories_entity_type_entity_id_changed_at ON status_histories (entity_type, entity_id, changed_at);

CREATE UNIQUE INDEX ix_suppliers_code ON suppliers (code);

CREATE UNIQUE INDEX ix_suppliers_tax_id ON suppliers (tax_id);

CREATE INDEX ix_technology_cards_approved_by_user_id ON technology_cards (approved_by_user_id);

CREATE INDEX ix_technology_cards_created_by_user_id ON technology_cards (created_by_user_id);

CREATE UNIQUE INDEX ix_technology_cards_product_id ON technology_cards (product_id) WHERE status = 3 AND is_active;

CREATE UNIQUE INDEX ix_technology_cards_product_id_version_number ON technology_cards (product_id, version_number);

CREATE UNIQUE INDEX ix_technology_step_parameters_technology_step_id_name ON technology_step_parameters (technology_step_id, name);

CREATE UNIQUE INDEX ix_technology_steps_technology_card_id_step_order ON technology_steps (technology_card_id, step_order);

CREATE UNIQUE INDEX ix_user_roles_code ON user_roles (code);

CREATE UNIQUE INDEX ix_user_roles_name ON user_roles (name);

CREATE OR REPLACE FUNCTION validate_recipe_total_before_approval()
RETURNS trigger
AS $$
DECLARE
    component_total numeric(10,2);
    IF NEW.status = 3 THEN
        SELECT COALESCE(SUM(percentage), 0)
        INTO component_total
        FROM recipe_components
        WHERE recipe_version_id = NEW.id;

        IF ROUND(component_total, 2) <> 100.00 THEN
            RAISE EXCEPTION
                'Cannot approve recipe version %, component total must equal 100%%. Actual total: %',
                NEW.id,
                component_total;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION validate_recipe_total_after_component_change()
RETURNS trigger
AS $$
DECLARE
    affected_recipe_version_id integer;
    current_status integer;
    component_total numeric(10,2);
    affected_recipe_version_id := COALESCE(NEW.recipe_version_id, OLD.recipe_version_id);

    SELECT status
    INTO current_status
    FROM recipe_versions
    WHERE id = affected_recipe_version_id;

    IF current_status = 3 THEN
        SELECT COALESCE(SUM(percentage), 0)
        INTO component_total
        FROM recipe_components
        WHERE recipe_version_id = affected_recipe_version_id;

        IF ROUND(component_total, 2) <> 100.00 THEN
            RAISE EXCEPTION
                'Approved recipe version % must keep component total equal to 100%%. Actual total: %',
                affected_recipe_version_id,
                component_total;

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION validate_production_batch_configuration()
RETURNS trigger
AS $$
DECLARE
    recipe_status integer;
    recipe_is_active boolean;
    technology_status integer;
    technology_is_active boolean;
    extruder_is_active boolean;
    extruder_technology_card_id integer;
    SELECT status, is_active
    INTO recipe_status, recipe_is_active
    FROM recipe_versions
    WHERE id = NEW.recipe_version_id
      AND product_id = NEW.product_id;

    IF NOT FOUND OR recipe_status <> 3 OR NOT recipe_is_active THEN
        RAISE EXCEPTION
            'Production batch % must use an active approved recipe version for product %',
            NEW.batch_number,
            NEW.product_id;

    SELECT status, is_active
    INTO technology_status, technology_is_active
    FROM technology_cards
    WHERE id = NEW.technology_card_id
      AND product_id = NEW.product_id;

    IF NOT FOUND OR technology_status <> 3 OR NOT technology_is_active THEN
        RAISE EXCEPTION
            'Production batch % must use an active approved technology card for product %',
            NEW.batch_number,
            NEW.product_id;

    IF NEW.extruder_program_id IS NOT NULL THEN
        SELECT is_active, technology_card_id
        INTO extruder_is_active, extruder_technology_card_id
        FROM extruder_programs
        WHERE id = NEW.extruder_program_id
          AND product_id = NEW.product_id;

        IF NOT FOUND OR NOT extruder_is_active THEN
            RAISE EXCEPTION
                'Production batch % must use an active extruder program for product %',
                NEW.batch_number,
                NEW.product_id;

        IF extruder_technology_card_id IS NOT NULL
           AND extruder_technology_card_id <> NEW.technology_card_id THEN
            RAISE EXCEPTION
                'Extruder program % is not linked to technology card %',
                NEW.extruder_program_id,
                NEW.technology_card_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION validate_batch_step_run_matches_batch()
RETURNS trigger
AS $$
DECLARE
    batch_technology_card_id integer;
    step_technology_card_id integer;
    SELECT technology_card_id
    INTO batch_technology_card_id
    FROM production_batches
    WHERE id = NEW.production_batch_id;

    SELECT technology_card_id
    INTO step_technology_card_id
    FROM technology_steps
    WHERE id = NEW.technology_step_id;

    IF batch_technology_card_id IS DISTINCT FROM step_technology_card_id THEN
        RAISE EXCEPTION
            'Step % does not belong to technology card of batch %',
            NEW.technology_step_id,
            NEW.production_batch_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION validate_batch_step_measurement_matches_run()
RETURNS trigger
AS $$
DECLARE
    run_step_id integer;
    parameter_step_id integer;
    SELECT technology_step_id
    INTO run_step_id
    FROM batch_technology_step_runs
    WHERE id = NEW.batch_technology_step_run_id;

    SELECT technology_step_id
    INTO parameter_step_id
    FROM technology_step_parameters
    WHERE id = NEW.technology_step_parameter_id;

    IF run_step_id IS DISTINCT FROM parameter_step_id THEN
        RAISE EXCEPTION
            'Measured parameter % does not belong to step run %',
            NEW.technology_step_parameter_id,
            NEW.batch_technology_step_run_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION validate_process_deviation_matches_run()
RETURNS trigger
AS $$
DECLARE
    run_batch_id integer;
    IF NEW.batch_technology_step_run_id IS NULL THEN
        RETURN NEW;

    SELECT production_batch_id
    INTO run_batch_id
    FROM batch_technology_step_runs
    WHERE id = NEW.batch_technology_step_run_id;

    IF run_batch_id IS DISTINCT FROM NEW.production_batch_id THEN
        RAISE EXCEPTION
            'Deviation step run % does not belong to production batch %',
            NEW.batch_technology_step_run_id,
            NEW.production_batch_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION validate_batch_raw_material_consumption()
RETURNS trigger
AS $$
DECLARE
    lot_status integer;
    lot_quantity_received numeric(18,3);
    total_used numeric(18,3);
BEGIN
    SELECT status, quantity_received
    INTO lot_status, lot_quantity_received
    FROM raw_material_lots lot
    WHERE id = NEW.raw_material_lot_id;

    IF lot_status <> 2 THEN
        RAISE EXCEPTION
            'Only approved raw material lots can be consumed. Lot % has status %',
            NEW.raw_material_lot_id,
            lot_status;
    END IF;

    IF TG_OP = 'UPDATE' THEN
        SELECT COALESCE(SUM(quantity_used), 0)
        INTO total_used
        FROM batch_raw_material_consumptions
        WHERE raw_material_lot_id = NEW.raw_material_lot_id
          AND NOT (
              production_batch_id = OLD.production_batch_id
              AND raw_material_lot_id = OLD.raw_material_lot_id
          );
    ELSE
        SELECT COALESCE(SUM(quantity_used), 0)
        INTO total_used
        FROM batch_raw_material_consumptions
        WHERE raw_material_lot_id = NEW.raw_material_lot_id;
    END IF;

    total_used := total_used + NEW.quantity_used;

    IF total_used > lot_quantity_received THEN
        RAISE EXCEPTION
            'Total consumption for raw material lot % exceeds received quantity',
            NEW.raw_material_lot_id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION validate_equipment_telemetry_matches_line()
RETURNS trigger
AS $$
DECLARE
    batch_line_id integer;
    equipment_line_id integer;
    IF NEW.equipment_id IS NULL THEN
        RETURN NEW;

    SELECT production_line_id
    INTO batch_line_id
    FROM production_batches
    WHERE id = NEW.production_batch_id;

    SELECT production_line_id
    INTO equipment_line_id
    FROM equipment
    WHERE id = NEW.equipment_id;

    IF batch_line_id IS DISTINCT FROM equipment_line_id THEN
        RAISE EXCEPTION
            'Equipment % does not belong to production line of batch %',
            NEW.equipment_id,
            NEW.production_batch_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION validate_laboratory_test_specification_matches_subject()
RETURNS trigger
AS $$
DECLARE
    lot_raw_material_id integer;
    batch_product_id integer;
    specification_subject_type integer;
    specification_raw_material_id integer;
    specification_product_id integer;
    SELECT subject_type, raw_material_id, product_id
    INTO specification_subject_type, specification_raw_material_id, specification_product_id
    FROM quality_specifications
    WHERE id = NEW.quality_specification_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Quality specification % does not exist',
            NEW.quality_specification_id;

    IF NEW.subject_type = 1 THEN
        SELECT raw_material_id
        INTO lot_raw_material_id
        FROM raw_material_lots
        WHERE id = NEW.raw_material_lot_id;

        IF specification_subject_type <> 1
           OR specification_raw_material_id IS DISTINCT FROM lot_raw_material_id THEN
            RAISE EXCEPTION
                'Laboratory test % uses a specification that does not match raw material lot %',
                NEW.test_number,
                NEW.raw_material_lot_id;
    ELSIF NEW.subject_type = 2 THEN
        SELECT product_id
        INTO batch_product_id
        FROM production_batches
        WHERE id = NEW.production_batch_id;

        IF specification_subject_type <> 2
           OR specification_product_id IS DISTINCT FROM batch_product_id THEN
            RAISE EXCEPTION
                'Laboratory test % uses a specification that does not match production batch %',
                NEW.test_number,
                NEW.production_batch_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION validate_laboratory_test_parameter_result_matches_specification()
RETURNS trigger
AS $$
DECLARE
    laboratory_test_specification_id integer;
    parameter_specification_id integer;
    IF NEW.quality_specification_parameter_id IS NULL THEN
        RETURN NEW;

    SELECT quality_specification_id
    INTO laboratory_test_specification_id
    FROM laboratory_tests
    WHERE id = NEW.laboratory_test_id;

    SELECT quality_specification_id
    INTO parameter_specification_id
    FROM quality_specification_parameters
    WHERE id = NEW.quality_specification_parameter_id;

    IF laboratory_test_specification_id IS DISTINCT FROM parameter_specification_id THEN
        RAISE EXCEPTION
            'Laboratory test parameter result % does not belong to specification of test %',
            NEW.quality_specification_parameter_id,
            NEW.laboratory_test_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION validate_quality_decision_matches_laboratory_test()
RETURNS trigger
AS $$
DECLARE
    test_subject_type integer;
    test_raw_material_lot_id integer;
    test_production_batch_id integer;
    SELECT subject_type, raw_material_lot_id, production_batch_id
    INTO test_subject_type, test_raw_material_lot_id, test_production_batch_id
    FROM laboratory_tests
    WHERE id = NEW.laboratory_test_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Laboratory test % does not exist for quality decision',
            NEW.laboratory_test_id;

    IF NEW.subject_type = 1 THEN
        IF test_subject_type <> 1
           OR test_raw_material_lot_id IS DISTINCT FROM NEW.raw_material_lot_id THEN
            RAISE EXCEPTION
                'Quality decision for raw material lot % must use a matching laboratory test',
                NEW.raw_material_lot_id;
    ELSIF NEW.subject_type = 2 THEN
        IF test_subject_type <> 2
           OR test_production_batch_id IS DISTINCT FROM NEW.production_batch_id THEN
            RAISE EXCEPTION
                'Quality decision for production batch % must use a matching laboratory test',
                NEW.production_batch_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_recipe_versions_validate_total_before_approval
BEFORE INSERT OR UPDATE OF status
ON recipe_versions
FOR EACH ROW
EXECUTE FUNCTION validate_recipe_total_before_approval();

CREATE TRIGGER trg_recipe_components_validate_total_after_change
AFTER INSERT OR UPDATE OR DELETE
ON recipe_components
FOR EACH ROW
EXECUTE FUNCTION validate_recipe_total_after_component_change();

CREATE TRIGGER trg_production_batches_validate_configuration
BEFORE INSERT OR UPDATE
ON production_batches
FOR EACH ROW
EXECUTE FUNCTION validate_production_batch_configuration();

CREATE TRIGGER trg_batch_technology_step_runs_validate_step
BEFORE INSERT OR UPDATE
ON batch_technology_step_runs
FOR EACH ROW
EXECUTE FUNCTION validate_batch_step_run_matches_batch();

CREATE TRIGGER trg_batch_step_measured_values_validate_parameter
BEFORE INSERT OR UPDATE
ON batch_step_measured_values
FOR EACH ROW
EXECUTE FUNCTION validate_batch_step_measurement_matches_run();

CREATE TRIGGER trg_process_deviations_validate_step_run
BEFORE INSERT OR UPDATE
ON process_deviations
FOR EACH ROW
EXECUTE FUNCTION validate_process_deviation_matches_run();

CREATE TRIGGER trg_batch_raw_material_consumptions_validate_usage
BEFORE INSERT OR UPDATE
ON batch_raw_material_consumptions
FOR EACH ROW
EXECUTE FUNCTION validate_batch_raw_material_consumption();

CREATE TRIGGER trg_equipment_telemetry_readings_validate_equipment
BEFORE INSERT OR UPDATE
ON equipment_telemetry_readings
FOR EACH ROW
EXECUTE FUNCTION validate_equipment_telemetry_matches_line();

CREATE TRIGGER trg_laboratory_tests_validate_specification
BEFORE INSERT OR UPDATE
ON laboratory_tests
FOR EACH ROW
EXECUTE FUNCTION validate_laboratory_test_specification_matches_subject();

CREATE TRIGGER trg_laboratory_test_parameter_results_validate_parameter
BEFORE INSERT OR UPDATE
ON laboratory_test_parameter_results
FOR EACH ROW
EXECUTE FUNCTION validate_laboratory_test_parameter_result_matches_specification();

CREATE TRIGGER trg_quality_decisions_validate_subject_test
BEFORE INSERT OR UPDATE
ON quality_decisions
FOR EACH ROW
EXECUTE FUNCTION validate_quality_decision_matches_laboratory_test();

